#yml添加配置,开启 hystrix
feign:
 hystrix:
   enabled: true
server:
  port: 80
spring:
  application:
    name: cloud-order-server

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
#    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
ribbon:
    #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
    ReadTimeout: 5000
    #指的是建立连接后服务器读取到可用资源所用的时间
    ConectTimeout: 5000
#logging:
#  level:
#    #feign日志以什么级别监控哪个接口
#    com.guo.springcloud.service.PaymentFeignService: debug



